"use client"

import Image from "next/image"
import { useCallback, useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { AnimatePresence, motion, useReducedMotion } from "motion/react"
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Copy, Lightbulb, Loader2, LogOut, RefreshCcw, Sparkles, Swords, Trophy, XCircle } from "lucide-react"
import type { X1Player, X1PublicMatch } from "@/lib/x1/types"

const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase()
function Player({ player, symbol, subject, active }: { player: X1Player | null; symbol: "X" | "O"; subject: string | null; active: boolean }) {
  const reduce = useReducedMotion()
  return <motion.div animate={active && !reduce ? { scale: [1, 1.015, 1] } : { scale: 1 }} transition={{ duration: .45 }} className={`flex min-w-0 items-center gap-3 rounded-2xl border p-3 transition ${active ? "border-[#50D05C] bg-[#50D05C]/10 shadow-sm" : "border-black/5 bg-white"}`}>{player?.image ? <Image unoptimized src={player.image} alt={`Foto de ${player.name}`} width={44} height={44} className="size-11 rounded-xl object-cover" /> : <div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-black text-xs font-black text-white">{player ? initials(player.name) : "…"}</div>}<div className="min-w-0 flex-1"><p className="truncate font-bold">{player?.name ?? "Aguardando jogador"}</p><p className="truncate text-xs text-black/45">{subject ?? "Matéria não escolhida"}</p></div><span className={`text-2xl font-black ${symbol === "X" ? "text-[#36ad42]" : "text-black"}`}>{symbol}</span></motion.div>
}

function TurnTimer({ endsAt, totalSeconds, onExpire }: { endsAt: string; totalSeconds: number; onExpire: () => void }) {
  const [seconds, setSeconds] = useState<number | null>(null)
  useEffect(() => {
    let expired = false
    const update = () => { const next = Math.max(0, Math.ceil((new Date(endsAt).getTime() - Date.now()) / 1000)); setSeconds(next); if (next === 0 && !expired) { expired = true; onExpire() } }
    const first = window.setTimeout(update, 0), timer = window.setInterval(update, 250)
    return () => { window.clearTimeout(first); window.clearInterval(timer) }
  }, [endsAt, onExpire])
  const percentage = seconds === null ? 100 : Math.min(100, (seconds / totalSeconds) * 100)
  return <div className="min-w-20"><div className="flex items-center justify-end gap-1.5 text-sm font-black"><Clock3 className={`size-4 ${seconds !== null && seconds <= 5 ? "text-red-400" : "text-[#50D05C]"}`} /><span>{seconds ?? "…"}s</span></div><div className="mt-1 h-1 overflow-hidden rounded-full bg-white/10"><div className={`h-full transition-[width] duration-200 ${seconds !== null && seconds <= 5 ? "bg-red-400" : "bg-[#50D05C]"}`} style={{ width: `${percentage}%` }} /></div></div>
}

export function X1Game({ code, initialMatch, userId, subjects }: { code: string; initialMatch: X1PublicMatch; userId: string; subjects: string[] }) {
  const router = useRouter(), [match, setMatch] = useState(initialMatch), [busy, setBusy] = useState(false), [error, setError] = useState(""), [feedback, setFeedback] = useState<{ correct: boolean; answer: string; explanation: string | null } | null>(null)
  const reduceMotion = useReducedMotion()
  const actionMotion = reduceMotion ? {} : { whileHover: { scale: 1.04, y: -1 }, whileTap: { scale: .96, y: 0 }, transition: { duration: .16 } }
  const refresh = useCallback(async () => { const response = await fetch(`/api/x1/${code}`, { cache: "no-store" }); if (response.ok) { const body: { match: X1PublicMatch } = await response.json(); setMatch(body.match) } }, [code])
  useEffect(() => { if (["FINISHED", "ABANDONED", "CANCELED"].includes(match.status)) return; const timer = window.setInterval(refresh, 1500); return () => window.clearInterval(timer) }, [match.status, refresh])
  async function choose(subject: string) { setBusy(true); setError(""); const response = await fetch(`/api/x1/${code}/subject`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject }) }); const body: { error?: string } = await response.json(); if (!response.ok) setError(body.error ?? "Não foi possível escolher."); await refresh(); setBusy(false) }
  async function cell(index: number) { setBusy(true); setError(""); const response = await fetch(`/api/x1/${code}/cell`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cell: index }) }); const body: { error?: string } = await response.json(); if (!response.ok) setError(body.error ?? "Não foi possível escolher a casa."); await refresh(); setBusy(false) }
  async function answer(value: string) { setBusy(true); setError(""); const response = await fetch(`/api/x1/${code}/answer`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answer: value }) }); const body: { correct?: boolean; correctAnswer?: string; explanation?: string | null; error?: string } = await response.json(); if (!response.ok) setError(body.error ?? "Não foi possível responder."); else setFeedback({ correct: Boolean(body.correct), answer: body.correctAnswer ?? "", explanation: body.explanation ?? null }); await refresh(); setBusy(false) }
  async function leave() { await fetch(`/api/x1/${code}/leave`, { method: "POST" }); router.push("/x1") }
  const mineIsX = match.playerX.id === userId, mySymbol = mineIsX ? "X" : "O", mySubject = mineIsX ? match.playerXSubject : match.playerOSubject, myTurn = match.status === "PLAYING" && match.currentTurnUserId === userId, ended = ["FINISHED", "ABANDONED", "CANCELED"].includes(match.status)
  return <div className="x1-screen mx-auto max-w-6xl"><motion.header initial={reduceMotion ? false : { opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="flex flex-wrap items-center justify-between gap-3"><motion.button {...actionMotion} onClick={() => router.push("/x1")} className="inline-flex items-center gap-2 text-sm font-semibold text-black/50 hover:text-black"><ArrowLeft className="size-4" /> Voltar</motion.button><motion.button {...actionMotion} onClick={() => navigator.clipboard.writeText(code)} className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-white px-4 py-2 text-sm font-bold shadow-sm">Sala <span className="tracking-[.18em]">{code}</span><Copy className="size-4" /></motion.button><motion.button {...actionMotion} onClick={leave} className="inline-flex items-center gap-2 text-sm font-semibold text-red-600"><LogOut className="size-4" /> Sair</motion.button></motion.header>
    <div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><motion.main initial={reduceMotion ? false : { opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="rounded-[2rem] bg-black p-5 text-white shadow-xl sm:p-8"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#50D05C]">X1 de conhecimento</p><h1 className="mt-2 text-2xl font-black">{match.status === "WAITING" ? "Aguardando adversário" : ended ? match.winner ? `${match.winner.name} venceu!` : "Deu velha!" : myTurn ? "Sua vez de jogar" : "Vez do adversário"}</h1></div>{match.status === "PLAYING" && match.turnEndsAt && match.turnTimeSeconds ? <TurnTimer endsAt={match.turnEndsAt} totalSeconds={match.turnTimeSeconds} onExpire={refresh} /> : match.status === "PLAYING" ? <span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold text-white/50">Sem limite</span> : null}</div>
      <div className="mt-4 flex flex-wrap gap-2 text-xs text-white/45"><span className="rounded-full bg-white/[.07] px-3 py-1">{match.turnTimeSeconds ? `${match.turnTimeSeconds}s por turno` : "Tempo livre"}</span>{match.allowCapture && <span className="inline-flex items-center gap-1 rounded-full bg-[#50D05C]/15 px-3 py-1 text-[#50D05C]"><RefreshCcw className="size-3" /> Captura ligada</span>}</div>
      <div className="mx-auto mt-8 grid max-w-xl grid-cols-3 gap-2 sm:gap-3" role="grid" aria-label="Tabuleiro de jogo da velha">{match.board.map((value, index) => { const canCapture = match.allowCapture && Boolean(value) && value !== mySymbol; const selectable = !value || canCapture; return <motion.button key={index} role="gridcell" aria-label={`Casa ${index + 1}${value ? ` marcada com ${value}${canCapture ? ", pode ser capturada" : ""}` : " vazia"}`} onClick={() => cell(index)} disabled={busy || !myTurn || Boolean(match.activeQuestion) || !selectable || ended} whileHover={!reduceMotion && myTurn && selectable ? { scale: 1.035 } : undefined} whileTap={!reduceMotion && myTurn && selectable ? { scale: .97 } : undefined} className={`relative aspect-square rounded-2xl border text-5xl font-black transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#50D05C] disabled:cursor-default sm:rounded-3xl sm:text-7xl ${value === "X" ? "border-[#50D05C]/40 bg-[#50D05C]/15 text-[#50D05C]" : value === "O" ? "border-white/20 bg-white/10 text-white" : myTurn && !match.activeQuestion ? "border-white/10 bg-white/[.06] hover:border-[#50D05C] hover:bg-[#50D05C]/10" : "border-white/5 bg-white/[.03] text-white/20"} ${canCapture && myTurn && !match.activeQuestion ? "ring-1 ring-amber-400/50 hover:border-amber-400" : ""}`}>{value}{canCapture && myTurn && !match.activeQuestion && <RefreshCcw className="absolute right-2 top-2 size-4 text-amber-400" />}</motion.button> })}</div>
      <p className="mt-6 text-center text-sm text-white/45">{match.activeQuestion ? "Responda à pergunta para conquistar a casa." : myTurn ? match.allowCapture ? "Escolha uma casa livre ou capture uma do adversário." : "Escolha uma casa livre." : match.status === "PLAYING" ? "A partida atualiza automaticamente." : "Compartilhe o código da sala."}</p></motion.main>
      <motion.aside initial={reduceMotion ? false : { opacity: 0, x: 16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .08 }} className="space-y-4"><Player player={match.playerX} symbol="X" subject={match.playerXSubject} active={match.currentTurnUserId === match.playerX.id} /><Player player={match.playerO} symbol="O" subject={match.playerOSubject} active={Boolean(match.playerO && match.currentTurnUserId === match.playerO.id)} />
        {match.status === "PREPARING" && !mySubject && <motion.section initial={reduceMotion ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="rounded-[2rem] border border-black/5 bg-white p-5 shadow-sm"><h2 className="font-bold">Escolha sua matéria</h2><p className="mt-1 text-sm text-black/45">Suas perguntas virão deste tema.</p><div className="mt-4 grid gap-2">{subjects.map((subject, index) => <motion.button key={subject} onClick={() => choose(subject)} disabled={busy} initial={reduceMotion ? false : { opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .04 }} whileHover={reduceMotion ? undefined : { x: 4, scale: 1.01 }} whileTap={reduceMotion ? undefined : { scale: .98 }} className="rounded-2xl border border-black/10 px-4 py-3 text-left text-sm font-semibold transition-colors hover:border-[#50D05C] hover:bg-[#50D05C]/10 disabled:opacity-50">{subject}</motion.button>)}</div></motion.section>}
        {match.status === "PREPARING" && mySubject && <motion.section initial={reduceMotion ? false : { opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} className="rounded-[2rem] bg-[#50D05C]/15 p-5 text-green-900"><Loader2 className="size-5 animate-spin motion-reduce:animate-none" /><h2 className="mt-3 font-bold">Matéria escolhida!</h2><p className="mt-1 text-sm opacity-70">Aguardando o outro jogador escolher.</p></motion.section>}
        {ended && <motion.section initial={reduceMotion ? false : { opacity: 0, y: 16, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} className="rounded-[2rem] bg-white p-6 text-center shadow-sm">{match.winner ? <motion.div initial={reduceMotion ? false : { rotate: -15, scale: .5 }} animate={{ rotate: 0, scale: 1 }}><Trophy className="mx-auto size-10 text-amber-500" /></motion.div> : <Swords className="mx-auto size-10 text-[#50D05C]" />}<h2 className="mt-3 text-xl font-black">{match.status === "CANCELED" ? "Sala cancelada" : match.winner ? match.winner.id === userId ? "Você venceu!" : "Seu adversário venceu" : "Empate"}</h2><motion.button {...actionMotion} onClick={() => router.push("/x1")} className="mt-5 w-full rounded-full bg-black px-5 py-3 font-bold text-white">Jogar novamente</motion.button></motion.section>}
        {error && <p role="alert" className="rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
      </motion.aside></div>
    {match.activeQuestion && <motion.div role="dialog" aria-modal="true" aria-labelledby="x1-question-title" className="fixed inset-0 z-40 flex items-center justify-center bg-black/65 p-4 backdrop-blur-sm sm:p-6" initial={reduceMotion ? false : { opacity: 0 }} animate={{ opacity: 1 }}><motion.section initial={reduceMotion ? false : { opacity: 0, y: 24, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ type: "spring", stiffness: 280, damping: 24 }} className="w-full max-w-xl rounded-[2rem] bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-[#50D05C]/15 px-3 py-1 text-xs font-bold text-green-800">{match.activeQuestion.subject}</span><span className="text-xs font-semibold text-black/40">Casa {match.activeQuestion.cell + 1}</span></div><h2 id="x1-question-title" className="mt-5 text-xl font-black leading-snug sm:text-2xl">{match.activeQuestion.question}</h2><p className="mt-2 text-sm text-black/45">Escolha uma alternativa para concluir sua jogada.</p><div className="mt-6 grid gap-3">{match.activeQuestion.options.map((option, index) => <motion.button key={option} onClick={() => answer(option)} disabled={busy} initial={reduceMotion ? false : { opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: reduceMotion ? 0 : .08 + index * .05 }} whileHover={reduceMotion ? undefined : { x: 4, scale: 1.01 }} whileTap={reduceMotion ? undefined : { scale: .98 }} className="flex items-center gap-3 rounded-2xl border border-black/10 px-4 py-3.5 text-left text-sm font-semibold transition-colors hover:border-[#50D05C] hover:bg-[#50D05C]/10 disabled:opacity-50"><span className="flex size-7 shrink-0 items-center justify-center rounded-lg bg-black text-xs font-black text-white">{String.fromCharCode(65 + index)}</span>{option}</motion.button>)}</div>{busy && <p className="mt-4 flex items-center justify-center gap-2 text-sm text-black/45"><Loader2 className="size-4 animate-spin motion-reduce:animate-none" /> Conferindo resposta…</p>}</motion.section></motion.div>}
    <AnimatePresence>
      {feedback && <motion.div role="dialog" aria-modal="true" aria-labelledby="x1-feedback-title" className="fixed inset-0 z-50 flex items-center justify-center bg-[#07110b]/75 p-4 backdrop-blur-md sm:p-6" initial={reduceMotion ? false : { opacity: 0 }} animate={{ opacity: 1 }} exit={reduceMotion ? undefined : { opacity: 0 }}>
        <motion.div initial={reduceMotion ? false : { opacity: 0, y: 34, scale: .9, rotate: feedback.correct ? -1.5 : 1.5 }} animate={{ opacity: 1, y: 0, scale: 1, rotate: 0 }} exit={reduceMotion ? undefined : { opacity: 0, y: 18, scale: .96 }} transition={{ type: "spring", stiffness: 280, damping: 22 }} className={`relative w-full max-w-md overflow-hidden rounded-[2rem] border bg-white shadow-[0_30px_100px_rgba(0,0,0,.38)] ${feedback.correct ? "border-[#50D05C]/30" : "border-[#ff6b6b]/25"}`}>
          <div aria-hidden="true" className={`absolute inset-x-0 top-0 h-32 ${feedback.correct ? "bg-gradient-to-b from-[#50D05C]/20" : "bg-gradient-to-b from-[#ff6b6b]/16"}`} />
          {!reduceMotion && [...Array(6)].map((_, index) => <motion.span key={index} aria-hidden="true" className={`absolute size-2 rounded-full ${feedback.correct ? "bg-[#50D05C]" : "bg-[#ff8a65]"}`} style={{ left: `${14 + index * 14}%`, top: 42 }} initial={{ opacity: 0, y: 8, scale: 0 }} animate={{ opacity: [0, .8, 0], y: [8, -28 - index % 2 * 12, -48], scale: [0, 1, .4] }} transition={{ duration: 1.4, delay: index * .08, ease: "easeOut" }} />)}
          <div className="relative p-6 text-center sm:p-8">
            <motion.div initial={reduceMotion ? false : { scale: .3, rotate: feedback.correct ? -24 : 18 }} animate={{ scale: 1, rotate: 0 }} transition={{ type: "spring", stiffness: 360, damping: 18, delay: .08 }} className={`mx-auto grid size-20 place-items-center rounded-[1.65rem] shadow-lg ${feedback.correct ? "bg-[#50D05C] text-white shadow-[#50D05C]/25" : "bg-[#ff5d5d] text-white shadow-red-400/25"}`}>
              {feedback.correct ? <CheckCircle2 className="size-11" strokeWidth={2.5} /> : <XCircle className="size-11" strokeWidth={2.5} />}
            </motion.div>
            <div className={`mx-auto mt-5 inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-black uppercase tracking-[.12em] ${feedback.correct ? "bg-[#50D05C]/12 text-green-700" : "bg-red-50 text-red-600"}`}><Sparkles className="size-3.5" />{feedback.correct ? "Boa jogada" : "Quase lá"}</div>
            <h2 id="x1-feedback-title" className="mt-3 text-3xl font-black tracking-[-.035em] text-[#111827]">{feedback.correct ? "Mandou bem!" : "Não foi dessa vez"}</h2>
            <p className="mt-2 text-sm leading-relaxed text-black/45">{feedback.correct ? "Você acertou e conquistou a casa." : "Sem problema — use esta resposta para a próxima jogada."}</p>
            <motion.div initial={reduceMotion ? false : { opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .18 }} className={`mt-6 rounded-2xl border p-4 text-left ${feedback.correct ? "border-[#50D05C]/20 bg-[#50D05C]/[.07]" : "border-amber-200 bg-amber-50/80"}`}>
              <p className="text-[11px] font-black uppercase tracking-[.14em] text-black/40">Resposta correta</p>
              <p className="mt-1 text-lg font-black text-[#111827]">{feedback.answer}</p>
              {feedback.explanation && <div className="mt-3 flex gap-2.5 border-t border-black/[.07] pt-3"><Lightbulb className="mt-0.5 size-4 shrink-0 text-amber-500" /><p className="text-sm leading-relaxed text-black/60">{feedback.explanation}</p></div>}
            </motion.div>
            <motion.button {...actionMotion} onClick={() => setFeedback(null)} autoFocus className={`mt-6 flex h-14 w-full cursor-pointer items-center justify-center gap-2 rounded-full font-black text-white shadow-lg transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 ${feedback.correct ? "bg-[#168f3e] shadow-green-700/20 hover:bg-[#117a34] focus-visible:outline-[#168f3e]" : "bg-[#111827] shadow-black/20 hover:bg-black focus-visible:outline-black"}`}>Continuar<ArrowRight className="size-5" /></motion.button>
          </div>
        </motion.div>
      </motion.div>}
    </AnimatePresence>
  </div>
}
