"use client"

import Image from "next/image"
import { useCallback, useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { ArrowLeft, CheckCircle2, Clock3, Copy, Loader2, LogOut, Swords, Trophy, XCircle } from "lucide-react"
import type { X1Player, X1PublicMatch } from "@/lib/x1/types"

const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase()
function Player({ player, symbol, subject, active }: { player: X1Player | null; symbol: "X" | "O"; subject: string | null; active: boolean }) {
  return <div className={`flex min-w-0 items-center gap-3 rounded-2xl border p-3 transition ${active ? "border-[#50D05C] bg-[#50D05C]/10" : "border-black/5 bg-white"}`}>{player?.image ? <Image unoptimized src={player.image} alt={`Foto de ${player.name}`} width={44} height={44} className="size-11 rounded-xl object-cover" /> : <div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-black text-xs font-black text-white">{player ? initials(player.name) : "…"}</div>}<div className="min-w-0 flex-1"><p className="truncate font-bold">{player?.name ?? "Aguardando jogador"}</p><p className="truncate text-xs text-black/45">{subject ?? "Matéria não escolhida"}</p></div><span className={`text-2xl font-black ${symbol === "X" ? "text-[#36ad42]" : "text-black"}`}>{symbol}</span></div>
}

export function X1Game({ code, initialMatch, userId, subjects }: { code: string; initialMatch: X1PublicMatch; userId: string; subjects: string[] }) {
  const router = useRouter(), [match, setMatch] = useState(initialMatch), [busy, setBusy] = useState(false), [error, setError] = useState(""), [feedback, setFeedback] = useState<{ correct: boolean; answer: string; explanation: string | null } | null>(null)
  const refresh = useCallback(async () => { const response = await fetch(`/api/x1/${code}`, { cache: "no-store" }); if (response.ok) { const body: { match: X1PublicMatch } = await response.json(); setMatch(body.match) } }, [code])
  useEffect(() => { if (["FINISHED", "ABANDONED", "CANCELED"].includes(match.status)) return; const timer = window.setInterval(refresh, 1500); return () => window.clearInterval(timer) }, [match.status, refresh])
  async function choose(subject: string) { setBusy(true); setError(""); const response = await fetch(`/api/x1/${code}/subject`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject }) }); const body: { error?: string } = await response.json(); if (!response.ok) setError(body.error ?? "Não foi possível escolher."); await refresh(); setBusy(false) }
  async function cell(index: number) { setBusy(true); setError(""); const response = await fetch(`/api/x1/${code}/cell`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cell: index }) }); const body: { error?: string } = await response.json(); if (!response.ok) setError(body.error ?? "Não foi possível escolher a casa."); await refresh(); setBusy(false) }
  async function answer(value: string) { setBusy(true); setError(""); const response = await fetch(`/api/x1/${code}/answer`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answer: value }) }); const body: { correct?: boolean; correctAnswer?: string; explanation?: string | null; error?: string } = await response.json(); if (!response.ok) setError(body.error ?? "Não foi possível responder."); else setFeedback({ correct: Boolean(body.correct), answer: body.correctAnswer ?? "", explanation: body.explanation ?? null }); await refresh(); setBusy(false) }
  async function leave() { await fetch(`/api/x1/${code}/leave`, { method: "POST" }); router.push("/x1") }
  const mineIsX = match.playerX.id === userId, mySubject = mineIsX ? match.playerXSubject : match.playerOSubject, myTurn = match.status === "PLAYING" && match.currentTurnUserId === userId, ended = ["FINISHED", "ABANDONED", "CANCELED"].includes(match.status)
  return <div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-3"><button onClick={() => router.push("/x1")} className="inline-flex items-center gap-2 text-sm font-semibold text-black/50 hover:text-black"><ArrowLeft className="size-4" /> Voltar</button><button onClick={() => navigator.clipboard.writeText(code)} className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-white px-4 py-2 text-sm font-bold">Sala <span className="tracking-[.18em]">{code}</span><Copy className="size-4" /></button><button onClick={leave} className="inline-flex items-center gap-2 text-sm font-semibold text-red-600"><LogOut className="size-4" /> Sair</button></header>
    <div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><main className="rounded-[2rem] bg-black p-5 text-white shadow-xl sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#50D05C]">X1 de conhecimento</p><h1 className="mt-2 text-2xl font-black">{match.status === "WAITING" ? "Aguardando adversário" : ended ? match.winner ? `${match.winner.name} venceu!` : "Deu velha!" : myTurn ? "Sua vez de jogar" : "Vez do adversário"}</h1></div>{match.status === "PLAYING" && <Clock3 className="size-6 text-white/35" />}</div>
      <div className="mx-auto mt-8 grid max-w-xl grid-cols-3 gap-2 sm:gap-3" role="grid" aria-label="Tabuleiro de jogo da velha">{match.board.map((value, index) => <button key={index} role="gridcell" aria-label={`Casa ${index + 1}${value ? ` marcada com ${value}` : " vazia"}`} onClick={() => cell(index)} disabled={busy || !myTurn || Boolean(match.activeQuestion) || Boolean(value) || ended} className={`aspect-square rounded-2xl border text-5xl font-black transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#50D05C] disabled:cursor-default sm:rounded-3xl sm:text-7xl ${value === "X" ? "border-[#50D05C]/40 bg-[#50D05C]/15 text-[#50D05C]" : value === "O" ? "border-white/20 bg-white/10 text-white" : myTurn && !match.activeQuestion ? "border-white/10 bg-white/[.06] hover:border-[#50D05C] hover:bg-[#50D05C]/10" : "border-white/5 bg-white/[.03] text-white/20"}`}>{value}</button>)}</div>
      <p className="mt-6 text-center text-sm text-white/45">{match.activeQuestion ? "Responda à pergunta para conquistar a casa." : myTurn ? "Escolha uma casa livre." : match.status === "PLAYING" ? "A partida atualiza automaticamente." : "Compartilhe o código da sala."}</p></main>
      <aside className="space-y-4"><Player player={match.playerX} symbol="X" subject={match.playerXSubject} active={match.currentTurnUserId === match.playerX.id} /><Player player={match.playerO} symbol="O" subject={match.playerOSubject} active={Boolean(match.playerO && match.currentTurnUserId === match.playerO.id)} />
        {match.status === "PREPARING" && !mySubject && <section className="rounded-[2rem] border border-black/5 bg-white p-5 shadow-sm"><h2 className="font-bold">Escolha sua matéria</h2><p className="mt-1 text-sm text-black/45">Suas perguntas virão deste tema.</p><div className="mt-4 grid gap-2">{subjects.map((subject) => <button key={subject} onClick={() => choose(subject)} disabled={busy} className="rounded-2xl border border-black/10 px-4 py-3 text-left text-sm font-semibold hover:border-[#50D05C] hover:bg-[#50D05C]/10 disabled:opacity-50">{subject}</button>)}</div></section>}
        {match.status === "PREPARING" && mySubject && <section className="rounded-[2rem] bg-[#50D05C]/15 p-5 text-green-900"><Loader2 className="size-5 animate-spin motion-reduce:animate-none" /><h2 className="mt-3 font-bold">Matéria escolhida!</h2><p className="mt-1 text-sm opacity-70">Aguardando o outro jogador escolher.</p></section>}
        {match.activeQuestion && <section className="rounded-[2rem] border border-black/5 bg-white p-5 shadow-lg"><span className="rounded-full bg-[#50D05C]/15 px-3 py-1 text-xs font-bold text-green-800">{match.activeQuestion.subject} · casa {match.activeQuestion.cell + 1}</span><h2 className="mt-4 text-lg font-bold leading-snug">{match.activeQuestion.question}</h2><div className="mt-4 grid gap-2">{match.activeQuestion.options.map((option) => <button key={option} onClick={() => answer(option)} disabled={busy} className="rounded-2xl border border-black/10 px-4 py-3 text-left text-sm font-semibold transition hover:border-[#50D05C] hover:bg-[#50D05C]/10 disabled:opacity-50">{option}</button>)}</div></section>}
        {ended && <section className="rounded-[2rem] bg-white p-6 text-center shadow-sm">{match.winner ? <Trophy className="mx-auto size-10 text-amber-500" /> : <Swords className="mx-auto size-10 text-[#50D05C]" />}<h2 className="mt-3 text-xl font-black">{match.status === "CANCELED" ? "Sala cancelada" : match.winner ? match.winner.id === userId ? "Você venceu!" : "Seu adversário venceu" : "Empate"}</h2><button onClick={() => router.push("/x1")} className="mt-5 w-full rounded-full bg-black px-5 py-3 font-bold text-white">Jogar novamente</button></section>}
        {error && <p role="alert" className="rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
      </aside></div>
    {feedback && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-5 backdrop-blur-sm"><div className="w-full max-w-md rounded-[2rem] bg-white p-7 text-center shadow-2xl">{feedback.correct ? <CheckCircle2 className="mx-auto size-14 text-[#50D05C]" /> : <XCircle className="mx-auto size-14 text-red-500" />}<h2 className="mt-4 text-2xl font-black">{feedback.correct ? "Resposta certa!" : "Não foi dessa vez"}</h2><p className="mt-2 text-sm text-black/50">Resposta correta: <strong className="text-black">{feedback.answer}</strong></p>{feedback.explanation && <p className="mt-2 text-sm text-black/50">{feedback.explanation}</p>}<button onClick={() => setFeedback(null)} autoFocus className="mt-6 w-full rounded-full bg-black px-5 py-3 font-bold text-white">Continuar</button></div></div>}
  </div>
}
