"use client"

import Image from "next/image"
import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react"
import { motion, useReducedMotion } from "motion/react"
import { Check, Clock3, Crown, Plus, RefreshCw, Search, Shield, Swords, Trophy, X } from "lucide-react"
import type { DuelDashboard, DuelUser, DuelView } from "@/lib/x1/types"

type Opponent = DuelUser & { maskedEmail: string }
const durations: Record<number, string> = { 24: "24 horas", 72: "3 dias", 168: "7 dias" }
const statuses: Record<DuelView["status"], string> = { PENDING: "Pendente", ACTIVE: "Em andamento", DECLINED: "Recusado", CANCELED: "Cancelado", COMPLETED: "Encerrado" }
const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase()
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—"

function Avatar({ user, dark = false }: { user: DuelUser; dark?: boolean }) {
  return user.image ? <Image unoptimized src={user.image} alt={`Foto de ${user.name}`} width={52} height={52} className="size-13 rounded-2xl object-cover" /> : <div aria-hidden="true" className={`flex size-13 items-center justify-center rounded-2xl text-sm font-black ${dark ? "bg-white/10 text-white" : "bg-[#50D05C]/15 text-green-800"}`}>{initials(user.name)}</div>
}

function Countdown({ endsAt }: { endsAt: string }) {
  const [label, setLabel] = useState("Calculando…")
  useEffect(() => {
    const update = () => {
      const seconds = Math.max(0, Math.floor((new Date(endsAt).getTime() - Date.now()) / 1000))
      const days = Math.floor(seconds / 86400), hours = Math.floor((seconds % 86400) / 3600), minutes = Math.floor((seconds % 3600) / 60)
      setLabel(seconds === 0 ? "Encerrando…" : `${days ? `${days}d ` : ""}${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`)
    }
    update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer)
  }, [endsAt])
  return <span suppressHydrationWarning>{label}</span>
}

function ActiveDuel({ duel, currentUserId, refresh, refreshing }: { duel: DuelView; currentUserId: string; refresh: () => void; refreshing: boolean }) {
  const width = Math.round((duel.challengerScore / Math.max(1, duel.challengerScore + duel.opponentScore)) * 100)
  const leader = duel.challengerScore === duel.opponentScore ? "Empate" : `${duel.challengerScore > duel.opponentScore ? duel.challenger.name : duel.opponent.name} está vencendo`
  return <section className="overflow-hidden rounded-[2rem] bg-black p-5 text-white shadow-xl sm:p-8">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#50D05C]">Batalha em andamento</p><h2 className="mt-2 text-2xl font-bold">{leader}</h2></div><button onClick={refresh} disabled={refreshing} className="inline-flex items-center gap-2 rounded-full border border-white/15 px-4 py-2 text-sm text-white/70 hover:bg-white/10 focus-visible:outline-2 focus-visible:outline-[#50D05C] disabled:opacity-50"><RefreshCw className={`size-4 ${refreshing ? "animate-spin motion-reduce:animate-none" : ""}`} /> Atualizar</button></div>
    <div className="mt-8 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center sm:gap-8">{[duel.challenger, duel.opponent].map((player, index) => <div key={player.id} className={`min-w-0 ${index === 1 ? "col-start-3" : "col-start-1"}`}><div className="mx-auto w-fit"><Avatar user={player} dark /></div><p className="mt-3 truncate font-semibold">{player.name}</p><p className="text-xs text-white/45">{player.id === currentUserId ? "Você" : "Oponente"}</p></div>)}<div className="col-start-2 row-start-1"><Swords className="mx-auto size-7 text-[#50D05C]" /><p className="mt-2 whitespace-nowrap text-xl font-black sm:text-3xl">{duel.challengerScore} <span className="text-white/30">x</span> {duel.opponentScore}</p><p className="text-xs text-white/40">XP</p></div></div>
    <div className="mt-8 flex h-3 overflow-hidden rounded-full bg-white/10" aria-label={`Placar: ${duel.challengerScore} a ${duel.opponentScore}`}><div className="bg-[#50D05C] transition-[width] motion-reduce:transition-none" style={{ width: `${width}%` }} /><div className="flex-1 bg-white/35" /></div>
    <div className="mt-5 flex flex-col gap-2 text-sm text-white/55 sm:flex-row sm:justify-between"><span className="inline-flex items-center gap-2"><Clock3 className="size-4 text-[#50D05C]" /> Termina em <strong className="text-white"><Countdown endsAt={duel.endsAt!} /></strong></span><span>{formatDate(duel.endsAt)}</span></div>
  </section>
}

function NewDuelModal({ close, created }: { close: () => void; created: () => Promise<void> }) {
  const reduce = useReducedMotion(), [query, setQuery] = useState(""), [results, setResults] = useState<Opponent[]>([]), [selected, setSelected] = useState<Opponent | null>(null), [duration, setDuration] = useState(24), [busy, setBusy] = useState(false), [searching, setSearching] = useState(false), [error, setError] = useState("")
  useEffect(() => {
    if (query.trim().length < 2) return
    const controller = new AbortController(), timer = window.setTimeout(async () => { setSearching(true); try { const response = await fetch(`/api/x1/opponents?q=${encodeURIComponent(query.trim())}`, { signal: controller.signal }); const body: { users?: Opponent[] } = await response.json(); if (response.ok) setResults(body.users ?? []) } finally { if (!controller.signal.aborted) setSearching(false) } }, 350)
    return () => { window.clearTimeout(timer); controller.abort() }
  }, [query])
  async function submit(event: FormEvent) { event.preventDefault(); if (!selected) return; setBusy(true); setError(""); const response = await fetch("/api/x1", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ opponentId: selected.id, durationHours: duration }) }); const body: { error?: string } = await response.json(); if (!response.ok) { setError(body.error ?? "Não foi possível enviar."); setBusy(false); return } await created(); close() }
  return <motion.div role="dialog" aria-modal="true" aria-labelledby="new-duel-title" className="fixed inset-0 z-50 flex items-end justify-center bg-black/55 backdrop-blur-sm sm:items-center sm:p-5" initial={reduce ? false : { opacity: 0 }} animate={{ opacity: 1 }} onMouseDown={(event) => { if (event.target === event.currentTarget) close() }}><motion.form onSubmit={submit} className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-t-[2rem] bg-white p-6 sm:rounded-[2rem] sm:p-8" initial={reduce ? false : { y: 30 }} animate={{ y: 0 }}>
    <div className="flex justify-between"><div><h2 id="new-duel-title" className="text-2xl font-bold">Novo desafio</h2><p className="mt-1 text-sm text-black/45">Escolha alguém e defina a duração.</p></div><button type="button" onClick={close} aria-label="Fechar" className="rounded-full p-2 hover:bg-black/5"><X /></button></div>
    <label className="mt-7 block text-sm font-semibold" htmlFor="opponent-search">Buscar oponente</label><div className="relative mt-2"><Search className="absolute left-4 top-3.5 size-5 text-black/30" /><input id="opponent-search" autoFocus value={query} onChange={(event) => { const value = event.target.value; setQuery(value); setSelected(null); if (value.trim().length < 2) setResults([]) }} placeholder="Nome ou e-mail" className="h-12 w-full rounded-2xl border border-black/10 bg-[#F6F5F1] pl-12 pr-4 outline-none focus:border-[#50D05C] focus:ring-4 focus:ring-[#50D05C]/10" /></div><p className="mt-2 text-xs text-black/40">Digite ao menos 2 caracteres. E-mails aparecem protegidos.</p>
    <div className="mt-3 space-y-2" aria-live="polite">{searching && <p className="py-3 text-center text-sm text-black/45">Buscando…</p>}{!searching && query.length >= 2 && results.length === 0 && <p className="py-3 text-center text-sm text-black/45">Nenhum estudante encontrado.</p>}{results.map((user) => <button type="button" key={user.id} onClick={() => setSelected(user)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left ${selected?.id === user.id ? "border-[#50D05C] bg-[#50D05C]/10" : "border-black/5 hover:bg-black/[.03]"}`}><Avatar user={user} /><span className="min-w-0 flex-1"><strong className="block truncate">{user.name}</strong><span className="text-xs text-black/45">{user.maskedEmail}</span></span>{selected?.id === user.id && <Check className="text-green-700" />}</button>)}</div>
    <fieldset className="mt-6"><legend className="text-sm font-semibold">Duração</legend><div className="mt-2 grid grid-cols-3 gap-2">{[24, 72, 168].map((hours) => <button type="button" key={hours} onClick={() => setDuration(hours)} aria-pressed={duration === hours} className={`rounded-2xl border px-2 py-3 text-sm font-semibold ${duration === hours ? "border-black bg-black text-white" : "border-black/10"}`}>{durations[hours]}</button>)}</div></fieldset>
    {error && <p role="alert" className="mt-5 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={!selected || busy} className="mt-7 w-full rounded-full bg-[#50D05C] px-5 py-3.5 font-bold disabled:opacity-45">{busy ? "Enviando…" : "Enviar desafio"}</button>
  </motion.form></motion.div>
}

function Section({ title, icon, children }: { title: string; icon: ReactNode; children: ReactNode }) { return <section className="mt-6 overflow-hidden rounded-[2rem] border border-black/5 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-black/5 px-5 py-4">{icon}<h2 className="text-lg font-bold">{title}</h2></div><div className="divide-y divide-black/5">{children}</div></section> }

export function X1Home({ initialData }: { initialData: DuelDashboard }) {
  const [data, setData] = useState(initialData), [modal, setModal] = useState(false), [busyId, setBusyId] = useState<string | null>(null), [refreshing, setRefreshing] = useState(false), [message, setMessage] = useState<{ error: boolean; text: string } | null>(null)
  const refresh = useCallback(async () => { setRefreshing(true); try { const response = await fetch("/api/x1", { cache: "no-store" }); const body: DuelDashboard & { error?: string } = await response.json(); if (!response.ok) throw new Error(body.error); setData(body) } catch (error) { setMessage({ error: true, text: error instanceof Error ? error.message : "Erro ao atualizar." }) } finally { setRefreshing(false) } }, [])
  async function act(id: string, action: "accept" | "decline" | "cancel") { setBusyId(id); setMessage(null); const response = await fetch(action === "cancel" ? `/api/x1/${id}` : `/api/x1/${id}/respond`, { method: action === "cancel" ? "DELETE" : "PATCH", headers: { "Content-Type": "application/json" }, body: action === "cancel" ? undefined : JSON.stringify({ action }) }); const body: { error?: string } = await response.json(); if (!response.ok) setMessage({ error: true, text: body.error ?? "Não foi possível concluir." }); else { setMessage({ error: false, text: action === "accept" ? "Desafio aceito. Valendo!" : action === "decline" ? "Convite recusado." : "Convite cancelado." }); await refresh() } setBusyId(null) }
  const hasAny = data.active.length + data.received.length + data.sent.length + data.history.length > 0
  const summaryCards = [{ label: "Vitórias", value: data.summary.wins, Icon: Trophy }, { label: "Derrotas", value: data.summary.losses, Icon: Shield }, { label: "Empates", value: data.summary.draws, Icon: Swords }, { label: "Ativos", value: data.summary.active, Icon: Clock3 }]
  return <div className="mx-auto max-w-6xl"><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full bg-[#50D05C]/15 px-3 py-1 text-sm font-bold text-green-800"><Swords className="size-4" /> Arena de produtividade</span><h1 className="mt-4 text-4xl font-black sm:text-5xl">Desafios X1</h1><p className="mt-2 max-w-2xl text-black/50">Desafie um colega e descubra quem conquista mais XP estudando.</p></div><button onClick={() => setModal(true)} className="inline-flex items-center justify-center gap-2 rounded-full bg-black px-6 py-3.5 font-bold text-white shadow-lg hover:bg-black/85"><Plus className="size-5 text-[#50D05C]" /> Novo desafio</button></header>
    <section aria-label="Resumo" className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{summaryCards.map(({ label, value, Icon }) => <div key={label} className="rounded-3xl border border-black/5 bg-white p-5 shadow-sm"><Icon className="size-5 text-[#50D05C]" /><p className="mt-4 text-3xl font-black">{value}</p><p className="text-sm text-black/45">{label}</p></div>)}</section>
    {message && <div aria-live="polite" className={`mt-5 rounded-2xl p-4 text-sm ${message.error ? "bg-red-50 text-red-700" : "bg-[#50D05C]/15 text-green-800"}`}>{message.text}</div>}<div className="mt-6 space-y-5">{data.active.map((duel) => <ActiveDuel key={duel.id} duel={duel} currentUserId={data.currentUserId} refresh={refresh} refreshing={refreshing} />)}</div>
    {!hasAny && <section className="mt-6 rounded-[2rem] border border-dashed border-black/15 bg-white px-6 py-14 text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-3xl bg-black text-[#50D05C]"><Swords className="size-8" /></div><h2 className="mt-5 text-2xl font-bold">Sua arena está pronta</h2><p className="mx-auto mt-2 max-w-md text-sm text-black/45">Convide um estudante e acumule XP. Só conta o que for ganho durante a batalha.</p><button onClick={() => setModal(true)} className="mt-6 rounded-full bg-[#50D05C] px-6 py-3 font-bold">Criar primeiro desafio</button></section>}
    {data.received.length > 0 && <Section title="Convites recebidos" icon={<Swords className="size-5 text-[#50D05C]" />}>{data.received.map((duel) => <div key={duel.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><Avatar user={duel.challenger} /><div className="flex-1"><p className="font-semibold">{duel.challenger.name} desafiou você</p><p className="text-sm text-black/45">{durations[duel.durationHours]} · {formatDate(duel.createdAt)}</p></div><div className="flex gap-2"><button onClick={() => act(duel.id, "decline")} disabled={busyId === duel.id} className="rounded-full border px-4 py-2 text-sm font-semibold disabled:opacity-50">Recusar</button><button onClick={() => act(duel.id, "accept")} disabled={busyId === duel.id} className="rounded-full bg-[#50D05C] px-4 py-2 text-sm font-bold disabled:opacity-50">{busyId === duel.id ? "Aguarde…" : "Aceitar"}</button></div></div>)}</Section>}
    {data.sent.length > 0 && <Section title="Desafios enviados" icon={<Clock3 className="size-5 text-[#50D05C]" />}>{data.sent.map((duel) => <div key={duel.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><Avatar user={duel.opponent} /><div className="flex-1"><p className="font-semibold">{duel.opponent.name}</p><p className="text-sm text-black/45">{statuses[duel.status]} · {durations[duel.durationHours]} · {formatDate(duel.createdAt)}</p></div>{duel.status === "PENDING" && <button onClick={() => act(duel.id, "cancel")} disabled={busyId === duel.id} className="rounded-full border border-red-200 px-4 py-2 text-sm font-semibold text-red-700 disabled:opacity-50">Cancelar convite</button>}</div>)}</Section>}
    {data.history.length > 0 && <Section title="Histórico" icon={<Trophy className="size-5 text-[#50D05C]" />}>{data.history.map((duel) => { const challengerIsMe = duel.challenger.id === data.currentUserId, opponent = challengerIsMe ? duel.opponent : duel.challenger, mine = challengerIsMe ? duel.challengerScore : duel.opponentScore, theirs = challengerIsMe ? duel.opponentScore : duel.challengerScore, result = duel.outcome === "WIN" ? "Vitória" : duel.outcome === "LOSS" ? "Derrota" : "Empate"; return <div key={duel.id} className="flex items-center gap-4 p-5"><Avatar user={opponent} /><div className="min-w-0 flex-1"><p className="truncate font-semibold">{opponent.name}</p><p className="text-sm text-black/45">{formatDate(duel.completedAt ?? duel.endsAt)}</p></div><div className="text-right"><p className="font-black">{mine} x {theirs} XP</p><p className={`text-sm font-bold ${duel.outcome === "WIN" ? "text-green-700" : duel.outcome === "LOSS" ? "text-red-600" : "text-amber-600"}`}>{duel.outcome === "WIN" && <Crown className="mr-1 inline size-4" />}{result}</p></div></div>})}</Section>}
    {modal && <NewDuelModal close={() => setModal(false)} created={refresh} />}
  </div>
}
