INSERT INTO "X1Question" ("id", "subject", "question", "options", "correctAnswer", "explanation", "difficulty", "source", "reviewStatus", "fingerprint", "topicId", "updatedAt") VALUES
('mat10','Matemática','Quanto é 25 dividido por 5?','["4","5","6","10"]','5','25 dividido em cinco partes iguais resulta em 5.','MEDIUM','MANUAL','APPROVED',md5(lower('Quanto é 25 dividido por 5?') || '|' || '["4","5","6","10"]'),'topic-matematica',CURRENT_TIMESTAMP),
('mat11','Matemática','Qual é o perímetro de um quadrado de lado 6?','["12","18","24","36"]','24','O perímetro é quatro vezes o lado: 4 × 6 = 24.','MEDIUM','MANUAL','APPROVED',md5(lower('Qual é o perímetro de um quadrado de lado 6?') || '|' || '["12","18","24","36"]'),'topic-matematica',CURRENT_TIMESTAMP),
('mat12','Matemática','Qual número representa 3/4 em decimal?','["0,25","0,5","0,75","1,25"]','0,75','Três dividido por quatro é igual a 0,75.','MEDIUM','MANUAL','APPROVED',md5(lower('Qual número representa 3/4 em decimal?') || '|' || '["0,25","0,5","0,75","1,25"]'),'topic-matematica',CURRENT_TIMESTAMP),
('por10','Português','Qual palavra é um substantivo próprio?','["cidade","Brasil","menino","escola"]','Brasil','Brasil nomeia especificamente um país e é substantivo próprio.','MEDIUM','MANUAL','APPROVED',md5(lower('Qual palavra é um substantivo próprio?') || '|' || '["cidade","Brasil","menino","escola"]'),'topic-portugues',CURRENT_TIMESTAMP),
('por11','Português','Em “Nós estudamos ontem”, qual é o pronome?','["Nós","estudamos","ontem","nenhum"]','Nós','Nós substitui os nomes das pessoas que falam.','MEDIUM','MANUAL','APPROVED',md5(lower('Em “Nós estudamos ontem”, qual é o pronome?') || '|' || '["Nós","estudamos","ontem","nenhum"]'),'topic-portugues',CURRENT_TIMESTAMP),
('por12','Português','Qual é o diminutivo de casa?','["casarão","casebre","casinha","casal"]','casinha','O sufixo -inha forma o diminutivo casinha.','MEDIUM','MANUAL','APPROVED',md5(lower('Qual é o diminutivo de casa?') || '|' || '["casarão","casebre","casinha","casal"]'),'topic-portugues',CURRENT_TIMESTAMP),
('cie10','Ciências','Qual parte da planta absorve água do solo?','["Flor","Folha","Raiz","Fruto"]','Raiz','As raízes absorvem água e sais minerais do solo.','MEDIUM','MANUAL','APPROVED',md5(lower('Qual parte da planta absorve água do solo?') || '|' || '["Flor","Folha","Raiz","Fruto"]'),'topic-ciencias',CURRENT_TIMESTAMP),
('cie11','Ciências','Qual é o satélite natural da Terra?','["Sol","Lua","Marte","Vênus"]','Lua','A Lua é o único satélite natural da Terra.','MEDIUM','MANUAL','APPROVED',md5(lower('Qual é o satélite natural da Terra?') || '|' || '["Sol","Lua","Marte","Vênus"]'),'topic-ciencias',CURRENT_TIMESTAMP),
('cie12','Ciências','Que mudança de estado transforma líquido em gás?','["Fusão","Condensação","Vaporização","Solidificação"]','Vaporização','Na vaporização, uma substância passa do estado líquido para o gasoso.','MEDIUM','MANUAL','APPROVED',md5(lower('Que mudança de estado transforma líquido em gás?') || '|' || '["Fusão","Condensação","Vaporização","Solidificação"]'),'topic-ciencias',CURRENT_TIMESTAMP),
('ger10','Conhecimentos Gerais','Qual oceano banha a costa leste do Brasil?','["Pacífico","Atlântico","Índico","Ártico"]','Atlântico','A costa brasileira é banhada pelo oceano Atlântico.','MEDIUM','MANUAL','APPROVED',md5(lower('Qual oceano banha a costa leste do Brasil?') || '|' || '["Pacífico","Atlântico","Índico","Ártico"]'),'topic-gerais',CURRENT_TIMESTAMP),
('ger11','Conhecimentos Gerais','Qual país tem Lisboa como capital?','["Espanha","Portugal","Itália","Grécia"]','Portugal','Lisboa é a capital de Portugal.','MEDIUM','MANUAL','APPROVED',md5(lower('Qual país tem Lisboa como capital?') || '|' || '["Espanha","Portugal","Itália","Grécia"]'),'topic-gerais',CURRENT_TIMESTAMP),
('ger12','Conhecimentos Gerais','Quantos dias possui um ano bissexto?','["364","365","366","367"]','366','O ano bissexto possui um dia adicional em fevereiro, totalizando 366 dias.','MEDIUM','MANUAL','APPROVED',md5(lower('Quantos dias possui um ano bissexto?') || '|' || '["364","365","366","367"]'),'topic-gerais',CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
